export interface MetaProps {
  title: string;
  description: string;
  canonical: string;
  noindex?: boolean;
  ogImage?: string;
}

interface MetaOptions {
  country?: Country;
  city?: City;
  baseUrl: string;
  path: string;
  locale: Locale;
}

import type { Country, City } from './geo';
import type { Locale } from '@/i18n/config';
import type { CountryScopedServiceSlug } from './labels';
import { SITE_NAME } from './constants';
import { getMetaTemplates } from '@/i18n/content/meta';

// og/<slug>.png is the ru default (unsuffixed); en/sr variants are
// generated by scripts/gen-og.mjs as og/<slug>-en.png / -sr.png. `slug` IS
// the filename — no separate lookup map needed.
export const OG_SUFFIX: Record<Locale, string> = { ru: '', en: '-en', sr: '-sr' };

export const ogImageFor = (baseUrl: string, slug: string, locale: Locale): string =>
  `${baseUrl}/og/${slug}${OG_SUFFIX[locale]}.png`;

// ponytail: vehicle-import has no dedicated OG asset yet (gen-og.mjs has no
// variant for it) — reuses vehicle-sourcing's image as a placeholder. One
// helper instead of the same string + comment copy-pasted on every
// vehicle-import page; swap the source key here once a real asset exists.
export const placeholderOgImage = (baseUrl: string, locale: Locale): string =>
  ogImageFor(baseUrl, 'vehicle-sourcing', locale);

// Assumes every current country/city takes the Serbian preposition "u"
// (locative-in). None of the 4 countries / 11 cities in countries.json /
// cities.json need "na" instead — if a future place does (e.g. an island or
// region), this needs a per-place preposition field, not a hardcoded one.
export function buildLocation(locale: Locale, country?: Country, city?: City): string {
  if (locale === 'en') {
    const name = city ? city.en.name : country!.en.name;
    return `in ${name}`;
  }
  const preposition = locale === 'ru' ? 'в' : 'u';
  const form = city ? city[locale].nameLocative : country![locale].nameLocative;
  return `${preposition} ${form}`;
}

export function generateMeta(
  service: CountryScopedServiceSlug,
  options: MetaOptions
): MetaProps {
  const { country, city, baseUrl, path, locale } = options;
  const canonical = `${baseUrl}${path}`;
  const ogImage = ogImageFor(baseUrl, service, locale);
  const location = buildLocation(locale, country, city);
  const { title, description } = getMetaTemplates(locale)[service](location);

  return {
    title: `${title} | ${SITE_NAME}`,
    description,
    canonical,
    ogImage,
  };
}

export function generateServiceSchema(name: string, areaServed: string | string[], url: string) {
  return {
    '@context': 'https://schema.org',
    '@type': 'Service',
    name,
    // Organization, not LocalBusiness: the business has no physical storefront
    // or service address — it operates cross-border, entirely through Telegram.
    provider: { '@type': 'Organization', name: SITE_NAME },
    areaServed,
    url,
  };
}

// Homepage/business-entity schema. Organization (not LocalBusiness — no address,
// no fixed service location) with sameAs pointing at the actual public profiles
// and a contactPoint for the real (Telegram-only) contact channel, instead of
// fabricating an address/telephone/geo the business doesn't have.
export function generateOrganizationSchema(options: {
  url: string;
  description: string;
  areaServed: string[];
  sameAs: string[];
  contactUrl: string;
}) {
  const { url, description, areaServed, sameAs, contactUrl } = options;
  return {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: SITE_NAME,
    description,
    url,
    logo: `${url}/apple-touch-icon.png`,
    areaServed,
    sameAs,
    contactPoint: {
      '@type': 'ContactPoint',
      contactType: 'customer service',
      url: contactUrl,
      availableLanguage: ['Russian', 'English'],
    },
  };
}

// Case bodies open with a hand-written, case-specific hook line — use it instead
// of a templated description so each case page reads as unique, not boilerplate.
export function excerptFromMarkdown(markdown: string, maxLen = 140): string {
  const firstParagraph = markdown.trim().split(/\n\s*\n/)[0] ?? '';
  const plain = firstParagraph
    .replace(/\*\*(.+?)\*\*/g, '$1')
    .replace(/[*_`]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
  if (plain.length <= maxLen) return plain;
  return plain.slice(0, maxLen).replace(/\s+\S*$/, '') + '…';
}

export function generateArticleSchema(options: {
  headline: string;
  description: string;
  image?: string;
  datePublished: Date;
  url: string;
}) {
  const { headline, description, image, datePublished, url } = options;
  return {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline,
    description,
    image,
    datePublished: datePublished.toISOString(),
    author: { '@type': 'Organization', name: SITE_NAME },
    publisher: { '@type': 'Organization', name: SITE_NAME },
    mainEntityOfPage: url,
  };
}
