import { leadStore } from './crm';

export const {
  updateLeads,
  readLeads,
  getLead,
  newStoredLead,
  insertLead,
  insertOrMergeLead,
  setTelegramMessage,
  setStatus,
  setPendingPrompt,
  findByPendingPrompt,
  findByCard,
  addNote,
  resolvePendingPrompt,
  archiveLead,
  unarchiveLead,
  resumeLead,
  postponeLead,
  deleteLead,
  claimCommission,
  confirmCommissionPayment,
  rejectCommissionPayment,
  searchLeads,
  getDuePostponed,
  readLedger,
  getBalance,
  listPayouts,
  addPayout,
  correctPayout,
  setPayoutPrompt,
  findPayoutByPrompt,
  findPastLead,
  addDraft,
  getDraft,
  findDraftByPrompt,
  updateDraft,
  discardDraft,
  confirmDraft,
  addSettlement,
  expireGhostLeads,
} = leadStore;

export {
  appendIncome,
  appendNote,
  canPostpone,
  getCommission,
  postponePatch,
  wonPatch,
  MAX_LIST_ROWS,
} from '@podbor/lead-crm';

export type {
  CommissionInfo,
  Draft,
  Income,
  LeadStatus,
  Payout,
  Settlement,
  Payment,
  PendingCommissionClaim,
  PendingPrompt,
  StoredLead,
} from '@podbor/lead-crm';
